### ISSUE TITLE
Improvements to Spinteractive

### ISSUE THREAD

**Issue by vheesen** [vheesen/Spinnaker#1]
Following improvments to spinteractive are needed:
- 'Information labels' ?
- The values for reduced chi^2 are not correct. They are too low, particularly for the spectral index.
- Set first_data_point_at_0_kpc = 1

With regards to the chi^2 discrepancy, I have put my own script to calculate reduced chi^2 into the folder 'spinteractive'. Just run 'python chi_NE.py' and it calculates the reduced chi^2 for both the first intensity (in this case LOFAR) and the spectral index. It assumes that the number of fit parameters n = 0, so that the degrees of freedom dof = N, where N is the number of data points. We might have to change n to depending on what we fit. For a constant advection speed it should be at least 2 or 3.

**Comment by amisk** [comment]
Corrected reduced chi^2 calculation.

Added effective beam option.

**Comment by vheesen** [comment]
Super! Just add the other two frequencies as well when you have time ;-) For me the parameter search does also not yet work.

**Comment by vheesen** [comment]
Just a little comment: the parameter 'FWHM_effective_beam' is not yet stored in the 'pars.last' file. So it is always set back to 1.1 kpc when spinteractive is launched. This could be ideally fixed and the parameter reverted to the same value as when spinteractive was last used.

**Comment by amisk** [comment]
fixed parameter search.
