### ISSUE TITLE
Spinteractive parameter search does not work

### ISSUE THREAD

**Issue by sarrvesh** [vheesen/Spinnaker#4]
Hey @amisk , 

I am using Spinteractive from the master branch. When I do parameter search with B1, hB2, and v0 enabled, I get the following error:

`/home/sarrvesh/Documents/Environment/workdir/local/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)`
`Exception in Tkinter callback`
`Traceback (most recent call last):`
`  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__`
`    return self.func(*args)`
`  File "spinteractive3_final.py", line 1003, in openfile1`
`    initial_plot()`
`  File "spinteractive3_final.py", line 286, in initial_plot`
`    minx = numpy.nanmin(d2[:,:,0])`
`IndexError: too many indices for array`
`Exception in Tkinter callback`
`Traceback (most recent call last):`
`  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__`
`    return self.func(*args)`
`  File "spinteractive3_final.py", line 1299, in search`
`    result = run_noplot(varstochange,i)`
`  File "spinteractive3_final.py", line 872, in run_noplot`
`    for i in range(0,max(int(d2[0,:,0]))+1,int(steps*lim)):`
`TypeError: only size-1 arrays can be converted to Python scalars`

Could you please have a look?

**Comment by amisk** [comment]
Hey, did you make sure the input data has the correct shape?

you could also send me the files so I can test it better.

**Comment by sarrvesh** [comment]
Yeah, both input files have the same shape. I've emailed you the files I used.

**Comment by sarrvesh** [comment]
This is fixed in the master branch through commit e24dee410ba3792d43c98be52d0ed1bd1d4cd70a. Thanks very much. I'll close this issue.
