### ISSUE TITLE
Using more than two frequencies does not work

### ISSUE THREAD

**Issue by vheesen** [vheesen/Spinnaker#7]
This is the error that I get when I use three frequencies:
TypeError: a float is required
Exception in Tkinter callback
Traceback (most recent call last):
  File "/export/scratch/hspc50/stnv047/a/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "spinteractive3_final.py", line 1151, in clicktab
    run()
  File "spinteractive3_final.py", line 699, in run
    chi_array[0] = chisq(d2[0,:,1]/numpy.nanmax(d2[0,:,1]),sim_int1)
TypeError: chisq() takes exactly 3 arguments (2 given)

This is the data that I use:

LOFAR, nu =1.4e8
0.0;6.1373;0.6125
465.42;4.0305;0.5120
930.84;2.6421;0.3440
1396.26;2.0140;0.2337
1861.68;1.6423;0.1842
2327.10;1.3018;0.1551
2792.52;0.9622;0.1288
3257.94;0.6336;0.1032
3723.37;0.3840;0.0797

VLA, nu=1.5e9
0.0;1.4598;0.1722
465.42;0.7328;0.1368
930.84;0.3299;0.0786
1396.26;0.1866;0.0464
1861.68;0.1157;0.0349
2327.10;0.0660;0.0293
2792.52;0.0318;0.0253
3257.94;0.0135;0.0225
3723.37;0.0088;0.0211

VLA, nu=6.0e9
0.0;0.7242;0.0779
465.42069680787847;0.5348;0.0628
930.8413944033957;0.2104;0.0368
1396.2620935741907;0.0401;0.0232
1861.682795107902;0.0083;0.0207
2327.10;0.0;0.0
2792.52;0.0;0.0
3257.94;0.0;0.0
3723.37;0.0;0.0

**Comment by amisk** [comment]
Should work now.

**Comment by vheesen** [comment]
Many thanks! Three frequencies work now. But can you check the second spectral index plot? The spectral indices are too flat although the shape of the profile looks OK. Is it possible that the wrong frequencies are used?

![spinnaker](https://user-images.githubusercontent.com/14839770/54292433-791bc580-45ae-11e9-8684-62fd7cffd2e3.png)

**Comment by vheesen** [comment]
My apologies. There was an issue with the data. Closed this issue.
